<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>uuid</key>
        <string>E07EC438-7B75-4437-8AA1-DA94C1E6EACD</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>name</key>
                <string>keyword.section</string>
                <key>match</key>
                <string>(?i)\[(Script Info|V4\+ Styles|Events)\]</string>
            </dict>
            <dict>
                <key>name</key>
                <string>string.ScriptInfo</string>
                <key>match</key>
                <string>(?i)^(Title|Original Script|Script\s*Type|Timer|PlayRes[XY]|WrapStyle|ScaledBorderAndShadow|Synch Point|Collisions|Audio URI|Video (Zoom Percent|File|Aspect Ratio|Position)|Scroll Position|Active Line|YCbCr Matrix|Last Style Storage)(?=\s*:)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>comment.Comment</string>
                <key>match</key>
                <string>(?i)^(;|Comment\s*:).*$</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.Format</string>
                <key>match</key>
                <string>(?i)^(Format)\s*:.*$</string>
            </dict>
            <dict>
                <key>name</key>
                <string>text</string>
                <key>match</key>
                <string>(?i)^(Style)\s*:\s*([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),(.*)$</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>string.Format</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.Name</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>support.function.Fontname</string>
                    </dict>
                    <key>4</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.Fontsize</string>
                    </dict>
                    <key>5</key>
                    <dict>
                        <key>name</key>
                        <string>comment.PrimaryColour</string>
                    </dict>
                    <key>6</key>
                    <dict>
                        <key>name</key>
                        <string>comment.SecondaryColour</string>
                    </dict>
                    <key>7</key>
                    <dict>
                        <key>name</key>
                        <string>comment.OutlineColour</string>
                    </dict>
                    <key>8</key>
                    <dict>
                        <key>name</key>
                        <string>comment.BackColour</string>
                    </dict>
                    <key>9</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.Bold</string>
                    </dict>
                    <key>10</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.Italic</string>
                    </dict>
                    <key>11</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.Underline</string>
                    </dict>
                    <key>12</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.StrikeOut</string>
                    </dict>
                    <key>13</key>
                    <dict>
                        <key>name</key>
                        <string>constant.numeric.ScaleX</string>
                    </dict>
                    <key>14</key>
                    <dict>
                        <key>name</key>
                        <string>constant.numeric.ScaleY</string>
                    </dict>
                    <key>15</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.Spacing</string>
                    </dict>
                    <key>16</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.Angle</string>
                    </dict>
                    <key>17</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.BorderStyle</string>
                    </dict>
                    <key>18</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.Outline</string>
                    </dict>
                    <key>19</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.Shadow</string>
                    </dict>
                    <key>20</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.Alignment</string>
                    </dict>
                    <key>21</key>
                    <dict>
                        <key>name</key>
                        <string>constant.numeric.MarginL</string>
                    </dict>
                    <key>22</key>
                    <dict>
                        <key>name</key>
                        <string>constant.numeric.MarginR</string>
                    </dict>
                    <key>23</key>
                    <dict>
                        <key>name</key>
                        <string>constant.numeric.MarginV</string>
                    </dict>
                    <key>24</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.Encoding</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>begin</key>
                <string>(?i)^(Dialogue)\s*:\s*([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),</string>
                <key>beginCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>string.Format</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.Layer</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>constant.numeric.Start</string>
                    </dict>
                    <key>4</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.End</string>
                    </dict>
                    <key>5</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.Style</string>
                    </dict>
                    <key>6</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.Name</string>
                    </dict>
                    <key>7</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.MarginL</string>
                    </dict>
                    <key>8</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.MarginR</string>
                    </dict>
                    <key>9</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.MarginV</string>
                    </dict>
                    <key>10</key>
                    <dict>
                        <key>name</key>
                        <string>constant.numeric.Effect</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>$</string>
                <key>name</key>
                <string>text</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>comment.fx</string>
                        <key>match</key>
                        <string>\{\\[^}]+\}</string>
                        <key>comment</key>
                        <string>ASS fx</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>keyword.newLine</string>
                        <key>match</key>
                        <string>\\N</string>
                    </dict>
                </array>
                <key>comment</key>
                <string>Dialogue line</string>
            </dict>
        </array>
        <key>name</key>
        <string>ASS_jf</string>
        <key>scopeName</key>
        <string>source</string>
        <key>fileTypes</key>
        <array>
            <string>ass</string>
        </array>
    </dict>
</plist>