<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>.gitignore</string>
    </array>
    <key>name</key>
    <string>gitignore_jf</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>name</key>
            <string>comment.Comment</string>
            <key>match</key>
            <string>^#.*$</string>
        </dict>
        <dict>
            <key>name</key>
            <string>storage</string>
            <key>match</key>
            <string>^!</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.gitignore</string>
    <key>uuid</key>
    <string>FF1825E8-6B1C-11D9-B883-000D98589BF8</string>
</dict>
</plist>
